/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CadastroDeConta;

import javax.swing.JOptionPane;

/**
 *
 * @author wende
 */
public class TelaCadastroDeContaComValidacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroDeContaComValidacoes
     */
    public TelaCadastroDeContaComValidacoes() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNomeDoCliente = new javax.swing.JLabel();
        lblNumeroDaConta = new javax.swing.JLabel();
        lblSaldoInicialDaConta = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtNomeDoCliente = new javax.swing.JTextField();
        txtNumeroDaConta = new javax.swing.JTextField();
        txtSaldoInicialDaConta = new javax.swing.JTextField();
        txfData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema IFBA - Restrições e Validação de Campos de Entrada");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Cadastro de Conta");

        lblNomeDoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeDoCliente.setText("Nome do Cliente:");

        lblNumeroDaConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumeroDaConta.setText("Número da Conta:");

        lblSaldoInicialDaConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSaldoInicialDaConta.setText("Saldo Inicial da Conta:");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data:");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtNomeDoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeDoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeDoClienteKeyTyped(evt);
            }
        });

        txtNumeroDaConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroDaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDaContaActionPerformed(evt);
            }
        });
        txtNumeroDaConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDaContaKeyTyped(evt);
            }
        });

        txtSaldoInicialDaConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSaldoInicialDaConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoInicialDaContaKeyTyped(evt);
            }
        });

        try {
            txfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroDaConta)
                        .addGap(31, 31, 31)
                        .addComponent(txtNumeroDaConta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeDoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeDoCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldoInicialDaConta)
                        .addGap(18, 18, 18)
                        .addComponent(txtSaldoInicialDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeDoCliente)
                    .addComponent(txtNomeDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroDaConta)
                    .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoInicialDaConta)
                    .addComponent(txtSaldoInicialDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        String nomeDoCliente = txtNomeDoCliente.getText();
        String numeroDaConta = txtNumeroDaConta.getText();
        String saldoInicialDaConta = txtSaldoInicialDaConta.getText();
        String data = txfData.getText();
        
        String menssagem = "Nome do Cliente: " + nomeDoCliente +
                "\nNúmero da Conta: " + numeroDaConta + 
                "\nSaldo Inicial da Conta: " + saldoInicialDaConta +
                "\nData: " + data;
        
        JOptionPane.showMessageDialog(this, menssagem);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNumeroDaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDaContaActionPerformed
       
       
                                        
     
    }//GEN-LAST:event_txtNumeroDaContaActionPerformed

    private void txtNomeDoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeDoClienteKeyTyped
        
        char c = evt.getKeyChar();
        
        if(!Character.isAlphabetic(c) && c !=' ')
        {
            evt.consume();
        
        }
    }//GEN-LAST:event_txtNomeDoClienteKeyTyped

    private void txtNumeroDaContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDaContaKeyTyped
        
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c))
        {
            
            evt.consume();
        
        }
    }//GEN-LAST:event_txtNumeroDaContaKeyTyped

    private void txtSaldoInicialDaContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoInicialDaContaKeyTyped
        
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c) && c !=  ',')
        {
            evt.consume();
        
        }
    }//GEN-LAST:event_txtSaldoInicialDaContaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeContaComValidacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeContaComValidacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeContaComValidacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeContaComValidacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeContaComValidacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblNomeDoCliente;
    private javax.swing.JLabel lblNumeroDaConta;
    private javax.swing.JLabel lblSaldoInicialDaConta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JFormattedTextField txfData;
    private javax.swing.JTextField txtNomeDoCliente;
    private javax.swing.JTextField txtNumeroDaConta;
    private javax.swing.JTextField txtSaldoInicialDaConta;
    // End of variables declaration//GEN-END:variables
}
